// src/constants/taxRules.ts
import { EntityType, TaxRule } from "@/types";

export const DEFAULT_TAX_RULES: TaxRule[] = [
  // Family and Other (Form 1040)
  {
    id: "rule_personal_income",
    entityType: EntityType.Family,
    budgetCategory: "Primary Income",
    taxCategory: "Wages",
    irsForm: "form_1040",
    defaultDeductiblePercentage: 0, // Income is taxable, not deductible
    tags: ["income", "taxable"],
  },
  {
    id: "rule_meals",
    entityType: EntityType.Family,
    budgetCategory: "Meals",
    taxCategory: "Meals",
    irsForm: "form_1040",
    defaultDeductiblePercentage: 50, // 50% for business-related meals
    tags: ["deductible", "personal"],
  },
  {
    id: "rule_mileage",
    entityType: EntityType.Family,
    budgetCategory: "Mileage",
    taxCategory: "Mileage",
    irsForm: "form_1040",
    defaultDeductiblePercentage: 100, // If business-related
    tags: ["deductible", "personal"],
  },

  // Business (Schedule C)
  {
    id: "rule_cogs",
    entityType: EntityType.Business,
    budgetCategory: "Inventory Purchasing",
    taxCategory: "Cost of Goods Sold",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_business_marketing",
    entityType: EntityType.Business,
    budgetCategory: "Marketing",
    taxCategory: "Advertising",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_platform_fees",
    entityType: EntityType.Business,
    budgetCategory: "Platform Fees",
    taxCategory: "Commissions and Fees",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_payment_processing",
    entityType: EntityType.Business,
    budgetCategory: "Payment Processing Fees",
    taxCategory: "Commissions and Fees",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_saas_fees",
    entityType: EntityType.Business,
    budgetCategory: "SaaS Fees",
    taxCategory: "Office Expense",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_shipping",
    entityType: EntityType.Business,
    budgetCategory: "Shipping",
    taxCategory: "Other Expenses",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_business_taxes",
    entityType: EntityType.Business,
    budgetCategory: "Taxes",
    taxCategory: "Taxes and Licenses",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_capital_expenses",
    entityType: EntityType.Business,
    budgetCategory: "Capital Expenses Savings",
    taxCategory: "Depreciation",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100, // Subject to depreciation rules
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_meals",
    entityType: EntityType.Business,
    budgetCategory: "Meals",
    taxCategory: "Meals",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 50,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_mileage",
    entityType: EntityType.Business,
    budgetCategory: "Mileage",
    taxCategory: "Car and Truck Expenses",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },
  {
    id: "rule_office_supplies",
    entityType: EntityType.Business,
    budgetCategory: "Office Supplies",
    taxCategory: "Office Expense",
    irsForm: "schedule_c",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "business_expense"],
  },

  // RentalProperty (Schedule E)
  {
    id: "rule_rental_repairs",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Maintenance",
    taxCategory: "Repairs",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "rental_repair"],
  },
  {
    id: "rule_rental_taxes",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Property Taxes",
    taxCategory: "Taxes",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "rental_expense"],
  },
  {
    id: "rule_rental_insurance",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Insurance",
    taxCategory: "Insurance",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "rental_expense"],
  },
  {
    id: "rule_rental_vacancy",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Vacancy",
    taxCategory: "Other Expenses",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "rental_expense"],
  },
  {
    id: "rule_rental_utilities",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Utilities",
    taxCategory: "Utilities",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "rental_expense"],
  },
  {
    id: "rule_rental_landscaping",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Landscaping",
    taxCategory: "Other Expenses",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "rental_expense"],
  },
  {
    id: "rule_rental_pest_control",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Pest Control",
    taxCategory: "Other Expenses",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100,
    tags: ["deductible", "rental_expense"],
  },
  {
    id: "rule_rental_capital_expenses",
    entityType: EntityType.RentalProperty,
    budgetCategory: "Capital Expenses Savings",
    taxCategory: "Depreciation",
    irsForm: "schedule_e",
    defaultDeductiblePercentage: 100, // Subject to depreciation rules
    tags: ["deductible", "rental_expense"],
  },
];